FROM postgres:9.4
COPY ./sql/create-all.sql /docker-entrypoint-initdb.d/10-create-all.sql
COPY ./sql/init-all-fr.sql /docker-entrypoint-initdb.d/20-init-all.sql
RUN chown -Rf postgres:postgres /docker-entrypoint-initdb.d && chmod -Rf 755 /docker-entrypoint-initdb.d
USER postgres
RUN ls -al /docker-entrypoint-initdb.d