version: "3"
services:
  database:
    image: orchestra-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nqidb
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
  web:
    image: orchestra-app
    ports:
      - "7001:8080"
    depends_on:
      - "database"
networks:
  webnet:
