
# !!! Database and tables must have been created before running this build

FROM ubuntu

RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN apt-get update && apt-get install -y postgresql-client

RUN pg_isready --help

# creating orchestra user
RUN useradd -ms /bin/bash orchestra

WORKDIR /home/orchestra/

# copying and unpacking archive
ADD orchestra-linux64-install-6.1.RC.tar.gz ./tmp
RUN chown -Rf orchestra:orchestra ./tmp
RUN mv ./tmp/orchestra-linux64-install-6.1.RC ./tmp/app
USER orchestra

WORKDIR /home/orchestra/tmp/app/

# copying install file
COPY ./install.properties ./

WORKDIR /home/orchestra/tmp/app

# installing app
RUN ./install.sh

WORKDIR /home/orchestra/

# removing temp files
RUN rm -Rf ./tmp

WORKDIR /home/orchestra/app/orchestra/applications/local/license
# adding the license

COPY ./nqi.license ./

WORKDIR /home/orchestra/app/orchestra/bin

ARG DB_HOST_NAME
ARG DB_PORT
RUN echo "#!/bin/bash" > ./waitAndRun.sh
RUN echo "pg_isready -h "$DB_HOST_NAME" -p "$DB_PORT" > /dev/null 2> /dev/null" >> ./waitAndRun.sh
RUN echo "while [ \$? != 0 ]; do" >> waitAndRun.sh
RUN echo "  echo 'Waiting to postgres to be up ...'" >> ./waitAndRun.sh
RUN echo "  sleep 2" >> ./waitAndRun.sh
RUN echo "  pg_isready -h "$DB_HOST_NAME" -p "$DB_PORT" > /dev/null 2> /dev/null" >> ./waitAndRun.sh
RUN echo "done" >> ./waitAndRun.sh
RUN echo "./nqi-service run" >> ./waitAndRun.sh

RUN chmod +x ./waitAndRun.sh
RUN cat ./waitAndRun.sh

# exposing port

EXPOSE 8080

# starting orchestra
CMD ./waitAndRun.sh
